# file      : unit-tests/regression/buildfile
# license   : MIT; see accompanying COPYING file

include ../../libexpat/

c.poptions += -DXML_BUILDING_EXPAT -DXML_TESTING
c.poptions =+ "-I$src_root/libexpat"

exe{driver}: {h c}{**} ../../libexpat/libue{expat} testscript
